//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication9
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Korp { get; set; }
        public string Socr { get; set; }
        public string Code { get; set; }
        public string Index { get; set; }
        public string Gninmb { get; set; }
        public string Uno { get; set; }
        public string Ocatd { get; set; }
    }
}
