//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication9
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MashaEntities : DbContext
    {
        public MashaEntities()
            : base("name=MashaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltNamesTable> AltNamesTables { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<KladrTable> KladrTables { get; set; }
        public virtual DbSet<MyRegion> MyRegions { get; set; }
        public virtual DbSet<SocrbaseTable> SocrbaseTables { get; set; }
        public virtual DbSet<StreetTable> StreetTables { get; set; }
    }
}
