//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication9
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocrbaseTable
    {
        public int Id { get; set; }
        public string Level { get; set; }
        public string Scname { get; set; }
        public string Kod_T_ST { get; set; }
    }
}
